apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server
spec:
  selector:
    matchLabels:
      app: web-server
  replicas: 1
  template:
    metadata:
      labels:
        app: web-server
    spec:
      containers:
        - name: web-server
          image: quay.io/myafk/interactive:stable
          command: ["interactive", "ingress"]
          env:
            - name: REDIS_MASTER_HOST
              value: "redis-master"
            - name: REDIS_SLAVE_HOST
              value: "redis-slave"
            - name: ELASTICSEARCH_HOSTS
              value: "http://elasticsearch:9200"
            - name: KUBERNETES_SERVICE_HOST
              value: "http://172.17.18.154/"
            - name: KUBERNETES_SERVICE_PORT
              value: "8443"
          ports:
            - containerPort: 8085